import { Type } from 'class-transformer';
import {
  IsBoolean,
  IsDefined,
  IsIn,
  IsInt,
  IsISO8601,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';

export class CreateSessionDto {
  @IsUUID()
  orderId!: string;

  @IsUUID()
  shippingCompanyId!: string;

  @IsOptional() @IsUUID()
  driverId?: string;

  @IsOptional() @IsUUID()
  vehicleId?: string;

  /** Used when the carrier swaps in a driver who is not in our master data. */
  @IsOptional() @IsString() @MaxLength(120)
  driverName?: string;

  @IsOptional() @IsString() @MaxLength(40)
  driverPhone?: string;

  @IsOptional() @IsString() @MaxLength(24)
  vehiclePlate?: string;

  @IsOptional() @IsInt() @Min(2) @Max(600)
  pingIntervalSec?: number;

  @IsOptional() @IsInt() @Min(5) @Max(1800)
  idleIntervalSec?: number;

  @IsOptional() @IsInt() @Min(0) @Max(5000)
  minDistanceM?: number;

  @IsOptional() @IsInt() @Min(1) @Max(240)
  maxLifetimeHours?: number;

  /** How long the claim code stays valid before the driver must ask for a new one. */
  @IsOptional() @IsInt() @Min(5) @Max(10080)
  claimTtlMinutes?: number;

  @IsOptional() @IsString() @MaxLength(2000)
  notes?: string;
}

export class UpdateSessionPolicyDto {
  @IsOptional() @IsInt() @Min(2) @Max(600)
  pingIntervalSec?: number;

  @IsOptional() @IsInt() @Min(5) @Max(1800)
  idleIntervalSec?: number;

  @IsOptional() @IsInt() @Min(0) @Max(5000)
  minDistanceM?: number;

  @IsOptional() @IsString() @MaxLength(2000)
  notes?: string;
}

export class SessionActionDto {
  @IsOptional() @IsString() @MaxLength(500)
  reason?: string;
}

export class ListSessionsQueryDto {
  @IsOptional()
  @IsIn(['DRAFT', 'ASSIGNED', 'CLAIMED', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'LIVE'])
  status?: string;

  @IsOptional() @IsUUID()
  shippingCompanyId?: string;

  @IsOptional() @IsUUID()
  customerId?: string;

  @IsOptional() @IsString() @MaxLength(120)
  search?: string;

  @IsOptional() @IsISO8601()
  from?: string;

  @IsOptional() @IsISO8601()
  to?: string;

  @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(200)
  limit?: number;

  @IsOptional() @Type(() => Number) @IsInt() @Min(0)
  offset?: number;
}

// -----------------------------------------------------------------------------
// Driver-facing
// -----------------------------------------------------------------------------

export class DeviceInfoDto {
  /** Stable per-install UUID generated by the app and kept in DataStore. */
  @IsString() @Length(8, 128)
  deviceId!: string;

  @IsOptional() @IsString() @MaxLength(128)
  fingerprint?: string;

  @IsOptional() @IsString() @MaxLength(64)
  manufacturer?: string;

  @IsOptional() @IsString() @MaxLength(64)
  model?: string;

  @IsOptional() @IsString() @MaxLength(32)
  osVersion?: string;

  @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100)
  sdkInt?: number;

  @IsOptional() @IsString() @MaxLength(32)
  appVersion?: string;

  @IsOptional() @Type(() => Number) @IsInt()
  appBuild?: number;

  /** Self-reported health flags — the dispatcher sees these before departure. */
  @IsOptional() @IsBoolean()
  batteryOptimisationIgnored?: boolean;

  @IsOptional() @IsBoolean()
  hasBackgroundLocation?: boolean;

  @IsOptional() @IsBoolean()
  hasExactAlarm?: boolean;
}

export class ClaimSessionDto {
  @IsString() @Length(4, 32)
  code!: string;

  /**
   * @IsDefined + @ValidateNested are load-bearing, not decoration.
   *
   * The global ValidationPipe runs with `whitelist: true`, which strips every
   * property that carries no *validation* decorator. @Type is a
   * class-transformer directive, so on its own it does not count — the whole
   * `device` object would be silently removed and the service would throw on
   * `dto.device.deviceId`. Covered by the e2e test.
   */
  @IsDefined()
  @ValidateNested()
  @Type(() => DeviceInfoDto)
  device!: DeviceInfoDto;
}

export class DriverRefreshDto {
  @IsString() @Length(16, 256)
  refreshToken!: string;

  @IsString() @Length(8, 128)
  deviceId!: string;
}

export class DriverEventDto {
  @IsIn([
    'STARTED', 'PAUSED', 'RESUMED', 'GPS_LOST', 'GPS_RECOVERED',
    'NETWORK_LOST', 'NETWORK_RECOVERED', 'BUFFER_OVERFLOW',
    'PERMISSION_REVOKED', 'BATTERY_LOW', 'SERVICE_KILLED',
    'SERVICE_RESTORED', 'NOTE',
  ])
  type!: string;

  @IsOptional() @IsISO8601()
  occurredAt?: string;

  @IsOptional() @IsString() @MaxLength(500)
  message?: string;

  @IsOptional()
  payload?: Record<string, unknown>;
}
